import { type AgreementItemRef } from "./AgreementItemRef";
import { type BillingAccountRef } from "./BillingAccountRef";
import { type CategoryRef } from "./CategoryRef";
import { type Characteristic } from "./Characteristic";
import { type GeographicAddress } from "./GeographicAddress";
import { type ProductOfferingRef } from "./ProductOfferingRef";
import { type ProductPrice } from "./ProductPrice";
import { type ProductRelationship } from "./ProductRelationship";
import { type ProductSpecificationRef } from "./ProductSpecificationRef";
import { type ProductTerm } from "./ProductTerm";
import { type RelatedParty } from "./RelatedParty";
import { type RelatedProductOrderItem } from "./RelatedProductOrderItem";
import { type ResourceRef } from "./ResourceRef";
import { type ServiceRef } from "./ServiceRef";

export interface ProductRefOrValue {
    id?: string;
    href?: string;
    description?: string;
    isBundle?: boolean;
    isCustomerVisible?: boolean;
    name?: string;
    orderDate?: string;
    productSerialNumber?: string;
    startDate?: string;
    terminationDate?: string;
    agreement?: AgreementItemRef[];
    billingAccount?: BillingAccountRef;
    place?: GeographicAddress[];
    product?: string[];
    productCharacteristic?: Characteristic[];
    productOffering?: ProductOfferingRef;
    productOrderItem?: RelatedProductOrderItem[];
    productPrice?: ProductPrice[];
    productRelationship?: ProductRelationship[];
    productSpecification?: ProductSpecificationRef;
    productTerm?: ProductTerm[];
    realizingResource?: ResourceRef[];
    realizingService?: ServiceRef[];
    relatedParty?: RelatedParty[];
    status?: string;
    '@baseType'?: string;
    '@schemaLocation'?: string;
    '@type'?: string;
    '@referredType'?: string;
    category?: CategoryRef[];
}