import { AgreementRef } from './AgreementRef';
import { AttachmentRefOrValue } from './AttachmentRefOrValue';
import { Authorization } from './Authorization';
import { BillingAccountRef } from './BillingAccountRef';
import { Characteristic } from './Characteristic';
import { ContactMedium } from './ContactMedium';
import { Note } from './Note';
import { PaymentRef } from './PaymentRef';
import { PriceAlteration } from './PriceAlteration';
import { ProductOfferingQualificationRef } from './ProductOfferingQualificationRef';
import { QuoteItem } from './QuoteItem';
import { QuotePrice } from './QuotePrice';
import { RelatedChannel } from './RelatedChannel';
import { RelatedParty } from './RelatedParty';
import { SalesOpportunityRef } from './SalesOpportunityRef';
import { SegmentRef } from './SegmentRef';
import { TimePeriod } from './TimePeriod';

export interface Quote {
  revision?: number;
  createdDate?: string;
  updatedDate?: string;
  createdBy?: string;
  updatedBy?: string;
  id: string;
  version?: string;
  href?: string;
  description?: string;
  state?: string;
  lastUpdate?: string;
  validFor?: TimePeriod;
  '@baseType'?: string;
  '@schemaLocation'?: string;
  '@type'?: string;
  aclRelatedParty?: RelatedParty[];
  category?: string;
  name?: string;
  effectiveQuoteCompletionDate?: string;
  expectedFulfillmentStartDate?: string;
  expectedQuoteCompletionDate?: string;
  externalId?: string;
  instantSyncQuote?: boolean;
  quoteDate?: string;
  requestedQuoteCompletionDate?: string;
  agreement?: AgreementRef[];
  authorization?: Authorization[];
  billingAccount?: BillingAccountRef[];
  contactMedium?: ContactMedium[];
  note?: Note[];
  productOfferingQualification?: ProductOfferingQualificationRef[];
  quoteItem?: QuoteItem[];
  relatedParty?: RelatedParty[];
  priceAlteration?: PriceAlteration[];
  quoteTotalPrice?: QuotePrice[];
  channel?: RelatedChannel[];
  payment?: PaymentRef[];
  expectedFulfillmentCompletionDate?: string;
  attachment?: AttachmentRefOrValue[];
  quoteCharacteristic?: Characteristic[];
  salesOpportunity?: SalesOpportunityRef;
  stage?: string;
  segment?: SegmentRef[];
  region?: string;
}
